version: 2
jobs:
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH
            - run: ssh ${SSH_USER}@${SSH_HOST} -oProxyCommand='ssh -W %h:%p ${BASTION_SSH_USER}@${BASTION_SSH_HOST}' 'mkdir -p ${PATH} && cd ${PATH} && git pull ${REPOSITORY}'
workflows:
    version: 2
    # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
    build_and_deploy:
        # build ジョブと deploy ジョブを呼び出す
        jobs:
            - deploy:
                requires:
                    # deploy ジョブより先に build ジョブを実行しろ！
                    - build
                # master ブランチに push された場合のみ deploy ジョブを実行する
                filters:
                    branches:
                        only: master
